cloud:
    aws:
        region:
            static: us-west-2

spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

endpoints:
  health:
    sensitive: false

server:
  port: 8080
  use-forward-headers: true

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}
    built-on: ${builtOn}

# Override the default security properties, defined in org.springframework.boot.autoconfigure.security.SecurityProperties
security:
  user:
    name: developer
    password: developer
  basic:
    enabled: false
    realm: Slurp-E

slurp-e:
  foo: bar
