cloud:
    aws:
        region:
            auto: false
            static: us-east-1

spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

endpoints:
    sensitive: false
    hypermedia:
        enabled: true
    docs:
        curies:
            enabled: false

server:
  port: 8080
  use-forward-headers: true

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}
    built-on: ${builtOn}

# Override the default security properties, defined in org.springframework.boot.autoconfigure.security.SecurityProperties
security:
  user:
    name: developer
    password: developer
  basic:
    enabled: false
    realm: Slurp-E

s3:
  foo: bar
